/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tubesgamesederhana;
import database.koneksiDatabase;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;//KALO ADA ERROR DIKASIK TAU
import javax.swing.JOptionPane;//MENAMPILKAN TULISAN "Registered Done"
import java.util.regex.*;
import java.awt.event.*;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
/**
 *
 * @author user
 */
public class frameLogin extends javax.swing.JFrame {

    static final String JDBC_DRIVER = "com.mysql.cj.jdbc.Driver";
    static final String DB_URL = "jdbc:mysql://localhost/db_slider_puzzle";
    static final String USER = "root";
    static final String PASS = "";
    
    static Connection conn;
    static Statement stmt;
    static ResultSet rs; 
    static int id_user;
    
    /**
     * Creates new form frameLogin
     */
    public frameLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        textFieldUsername = new javax.swing.JTextField();
        password = new javax.swing.JLabel();
        jButtonLogin = new javax.swing.JButton();
        jButtonRegister = new javax.swing.JButton();
        belumPunyaAkun = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(596, 326));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel1.setLayout(null);

        judul.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        judul.setForeground(new java.awt.Color(255, 255, 255));
        judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul.setText("SLIDER PUZZLE");
        judul.setToolTipText("");
        jPanel1.add(judul);
        judul.setBounds(140, 10, 281, 41);

        username.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setText("USERNAME");
        jPanel1.add(username);
        username.setBounds(20, 90, 120, 28);

        textFieldUsername.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        textFieldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldUsernameActionPerformed(evt);
            }
        });
        jPanel1.add(textFieldUsername);
        textFieldUsername.setBounds(20, 120, 200, 30);

        password.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setText("PASSWORD");
        jPanel1.add(password);
        password.setBounds(20, 170, 120, 28);

        jButtonLogin.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jButtonLogin.setText("LOGIN");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLogin);
        jButtonLogin.setBounds(70, 250, 90, 25);

        jButtonRegister.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jButtonRegister.setText("REGISTRASI AKUN");
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRegister);
        jButtonRegister.setBounds(380, 270, 185, 25);

        belumPunyaAkun.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        belumPunyaAkun.setForeground(new java.awt.Color(255, 255, 255));
        belumPunyaAkun.setText("BELUM PUNYA AKUN?");
        jPanel1.add(belumPunyaAkun);
        belumPunyaAkun.setBounds(400, 250, 150, 17);

        jPasswordField1.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(20, 200, 200, 30);

        jLabel9.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(jLabel9);
        jLabel9.setBounds(75, 265, 0, 0);

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambarProgram/puzzle (2).png"))); // NOI18N
        jPanel1.add(Logo);
        Logo.setBounds(300, 90, 128, 128);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambarProgram/thumbs-up (1).png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(440, 90, 130, 130);

        jToggleButton1.setBackground(new java.awt.Color(102, 102, 255));
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambarProgram/Eye-30px.png"))); // NOI18N
        jToggleButton1.setBorderPainted(false);
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1);
        jToggleButton1.setBounds(220, 200, 30, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldUsernameActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        // TODO add your handling code here:
            dispose();    
            frameRegister rg = new frameRegister();
            rg.setVisible(true);
            rg.pack();
            rg.setLocationRelativeTo(null);
            rg.setDefaultCloseOperation(frameRegister.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jButtonRegisterActionPerformed

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        // TODO add your handling code here:
    String username_form;    
    String password_form;
    String username_sql = null;
    String password_sql = null;
       
    username_form = textFieldUsername.getText();
    password_form = jPasswordField1.getText();

    try{
               Class.forName(JDBC_DRIVER);
               
               conn = DriverManager.getConnection(DB_URL, USER, PASS);
               stmt = conn.createStatement();
               
               String sql = "SELECT id_user, username_user, password_user FROM tb_user";
               
               rs = stmt.executeQuery(sql);
               while(rs.next()){                   
                   id_user = rs.getInt("id_user");
                   username_sql = rs.getString("username_user");
                   password_sql = rs.getString("password_user");
                   
                   if(username_form.equals(username_sql) && password_form.equals(password_sql)){
                        break;
                   }
           
               }
                
        }catch (Exception e) {
            e.printStackTrace();
            
        }
        try{
            String sql = "INSERT INTO tb_progres_3x3 (id_user) VALUES (%d)";
            sql = String.format(sql,id_user);
            stmt.execute(sql);
            stmt.close();
            conn.close(); 
        }catch (Exception e) {
            e.printStackTrace();
            
        }
        try{
            String sql = "INSERT INTO tb_progres_4x4 (id_user) VALUES (%d)";
            sql = String.format(sql,id_user);
            stmt.execute(sql);
            stmt.close();
            conn.close(); 
        }catch (Exception e) {
            e.printStackTrace();
        }        
    
        if(username_form.equals(username_sql) && password_form.equals(password_sql)){
                dispose();
                frameMainmenu hm = new frameMainmenu();
                hm.setVisible(true);
                hm.pack();
                hm.setLocationRelativeTo(null);
                hm.setDefaultCloseOperation(frameMainmenu.EXIT_ON_CLOSE);       
                       
        }
        else{
        JOptionPane.showMessageDialog(null,"Gagal, Username atau Password salah");
        }
    
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        if(jToggleButton1.isSelected())
        jPasswordField1.setEchoChar((char)0);
        else
        jPasswordField1.setEchoChar('•');
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel belumPunyaAkun;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel password;
    private javax.swing.JTextField textFieldUsername;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
