/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tubesgamesederhana;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.util.Arrays;
import java.util.Random;

/**
 *
 * @author user
 */
public class framePuzzle extends javax.swing.JFrame {
    
    
    /**
     * Creates new form framePuzzle
     */
    public framePuzzle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        Kembali = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        judul = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton17 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(664, 427));

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 255));
        jButton1.setText("1");
        jButton1.setPreferredSize(new java.awt.Dimension(0, 0));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 255));
        jButton2.setText("2");
        jButton2.setPreferredSize(new java.awt.Dimension(0, 0));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 51, 255));
        jButton3.setText("3");
        jButton3.setPreferredSize(new java.awt.Dimension(0, 0));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(51, 51, 255));
        jButton4.setText("4");
        jButton4.setPreferredSize(new java.awt.Dimension(0, 0));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(51, 51, 255));
        jButton5.setText("5");
        jButton5.setPreferredSize(new java.awt.Dimension(0, 0));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(51, 51, 255));
        jButton6.setText("6");
        jButton6.setPreferredSize(new java.awt.Dimension(0, 0));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(51, 51, 255));
        jButton7.setText("7");
        jButton7.setPreferredSize(new java.awt.Dimension(0, 0));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jButton8.setForeground(new java.awt.Color(51, 51, 255));
        jButton8.setText("8");
        jButton8.setPreferredSize(new java.awt.Dimension(0, 0));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jButton9.setForeground(new java.awt.Color(51, 51, 255));
        jButton9.setText("9");
        jButton9.setPreferredSize(new java.awt.Dimension(0, 0));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(255, 255, 255));
        jButton10.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jButton10.setForeground(new java.awt.Color(51, 51, 255));
        jButton10.setText("10");
        jButton10.setPreferredSize(new java.awt.Dimension(0, 0));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(255, 255, 255));
        jButton11.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jButton11.setForeground(new java.awt.Color(51, 51, 255));
        jButton11.setText("11");
        jButton11.setPreferredSize(new java.awt.Dimension(0, 0));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(255, 255, 255));
        jButton12.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jButton12.setForeground(new java.awt.Color(51, 51, 255));
        jButton12.setText("12");
        jButton12.setPreferredSize(new java.awt.Dimension(0, 0));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(255, 255, 255));
        jButton13.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jButton13.setForeground(new java.awt.Color(51, 51, 255));
        jButton13.setText("13");
        jButton13.setPreferredSize(new java.awt.Dimension(0, 0));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setBackground(new java.awt.Color(255, 255, 255));
        jButton14.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jButton14.setForeground(new java.awt.Color(51, 51, 255));
        jButton14.setText("14");
        jButton14.setPreferredSize(new java.awt.Dimension(0, 0));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setBackground(new java.awt.Color(255, 255, 255));
        jButton15.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jButton15.setForeground(new java.awt.Color(51, 51, 255));
        jButton15.setText("15");
        jButton15.setPreferredSize(new java.awt.Dimension(0, 0));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setBackground(new java.awt.Color(255, 255, 255));
        jButton16.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jButton16.setForeground(new java.awt.Color(51, 51, 255));
        jButton16.setPreferredSize(new java.awt.Dimension(0, 0));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        Kembali.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        Kembali.setText("KEMBALI");
        Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembaliActionPerformed(evt);
            }
        });

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambarProgram/puzzle (2).png"))); // NOI18N

        judul.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        judul.setForeground(new java.awt.Color(255, 255, 255));
        judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul.setText("SLIDER PUZZLE");

        jPanel2.setLayout(null);

        jButton17.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jButton17.setText("RESET");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logo)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton17)
                                .addGap(31, 31, 31))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(Kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(judul, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(90, 90, 90))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(judul)
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(logo))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton17)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Kembali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    static final String JDBC_DRIVER = "com.mysql.cj.jdbc.Driver";
    static final String DB_URL = "jdbc:mysql://localhost/db_slider_puzzle";
    static final String USER = "root";
    static final String PASS = "";
    
    static Connection conn;
    static Statement stmt;
    static ResultSet rs;     
    
    public void gantiRandom(){
            int[] array = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15 };

            Random rand = new Random();

            //https://www.journaldev.com/32661/shuffle-array-java
            for (int i = 0; i < array.length; i++) {
                    int randomIndexToSwap = rand.nextInt(array.length);
                    int temp = array[randomIndexToSwap];
                    array[randomIndexToSwap] = array[i];
                    array[i] = temp;
            }
            
            jButton1.setText(array[0]+"");
            jButton2.setText(array[1]+"");
            jButton3.setText(array[2]+"");
            jButton4.setText(array[3]+"");
            jButton5.setText(array[4]+"");
            jButton6.setText(array[5]+"");
            jButton7.setText(array[6]+"");
            jButton8.setText(array[7]+"");
            jButton9.setText(array[8]+"");
            jButton10.setText(array[9]+"");
            jButton11.setText(array[10]+"");
            jButton12.setText(array[11]+"");
            jButton13.setText(array[12]+"");
            jButton14.setText(array[13]+"");
            jButton15.setText(array[14]+"");
            jButton16.setText("");
            
            System.out.println(Arrays.toString(array));
    }
     
        public void gantiSave(){
        
        jButton1.setText("");
        jButton2.setText("");
        jButton3.setText("");
        jButton4.setText("");
        jButton5.setText("");
        jButton6.setText("");
        jButton7.setText("");
        jButton8.setText("");
        jButton9.setText("");
        jButton10.setText("");
        jButton11.setText("");
        jButton12.setText("");
        jButton13.setText("");
        jButton14.setText("");
        jButton15.setText("");
        jButton16.setText("");
        
        try{
            Class.forName(JDBC_DRIVER);

            conn = DriverManager.getConnection(DB_URL, USER, PASS);
            stmt = conn.createStatement();  
            
               String sql = "SELECT button1, button2, button3, button4, button5, button6, button7, button8, button9, button10, button11, button12, button13, button14, button15, button16 FROM tb_progres_4x4 where id_user = %d ";
               sql = String.format(sql,frameLogin.id_user);
               
               rs = stmt.executeQuery(sql);
               while(rs.next()){
                   if(rs.getInt("button1")!=0)
                        jButton1.setText(rs.getInt("button1")+"");
                   if(rs.getInt("button2")!=0)
                        jButton2.setText(rs.getInt("button2")+"");
                   if(rs.getInt("button3")!=0)
                        jButton3.setText(rs.getInt("button3")+"");
                   if(rs.getInt("button4")!=0)
                        jButton4.setText(rs.getInt("button4")+"");
                   if(rs.getInt("button5")!=0)
                        jButton5.setText(rs.getInt("button5")+"");
                   if(rs.getInt("button6")!=0)
                        jButton6.setText(rs.getInt("button6")+"");
                   if(rs.getInt("button7")!=0)
                        jButton7.setText(rs.getInt("button7")+"");
                   if(rs.getInt("button8")!=0)
                        jButton8.setText(rs.getInt("button8")+"");
                   if(rs.getInt("button9")!=0)
                        jButton9.setText(rs.getInt("button9")+"");
                   if(rs.getInt("button10")!=0)
                        jButton10.setText(rs.getInt("button10")+"");                   
                   if(rs.getInt("button11")!=0)
                        jButton11.setText(rs.getInt("button11")+"");                   
                   if(rs.getInt("button12")!=0)
                        jButton12.setText(rs.getInt("button12")+"");                   
                   if(rs.getInt("button13")!=0)
                        jButton13.setText(rs.getInt("button13")+"");                   
                   if(rs.getInt("button14")!=0)
                        jButton14.setText(rs.getInt("button14")+"");                   
                   if(rs.getInt("button15")!=0)
                        jButton15.setText(rs.getInt("button15")+"");                   
                   if(rs.getInt("button16")!=0)
                        jButton16.setText(rs.getInt("button16")+"");                   
               }           
            
        }catch (Exception e) {
            e.printStackTrace();
        }     
       
    }    

    
    private void cekSave(){
        String tombol_1 = jButton1.getText();
        String tombol_2 = jButton2.getText();
        String tombol_3 = jButton3.getText();
        String tombol_4 = jButton4.getText();
        String tombol_5 = jButton5.getText();
        String tombol_6 = jButton6.getText();
        String tombol_7 = jButton7.getText();
        String tombol_8 = jButton8.getText();
        String tombol_9 = jButton9.getText();
        String tombol_10 = jButton10.getText();
        String tombol_11 = jButton11.getText();
        String tombol_12 = jButton12.getText();
        String tombol_13 = jButton13.getText();
        String tombol_14 = jButton14.getText();
        String tombol_15 = jButton15.getText();
        String tombol_16 = jButton16.getText();
        int status = 0;
        
        try{
            Class.forName(JDBC_DRIVER);

            conn = DriverManager.getConnection(DB_URL, USER, PASS);
            stmt = conn.createStatement();  
            
            String sql = " UPDATE tb_progres_4x4 SET status=1, button1='%s', button2='%s', button3='%s', button4='%s', button5='%s', button6='%s', button7='%s', button8='%s', button9='%s',button10='%s',button11='%s',button12='%s',button13='%s',button14='%s',button15='%s',button16='%s' WHERE id_user=%d" ;
            sql = String.format(sql,tombol_1,tombol_2,tombol_3,tombol_4,tombol_5,tombol_6,tombol_7,tombol_8,tombol_9,tombol_10,tombol_11,tombol_12,tombol_13,tombol_14,tombol_15,tombol_16,frameLogin.id_user);
            stmt.execute(sql);
            stmt.close();
            conn.close(); 
            
        }catch (Exception e) {
            e.printStackTrace();
        }        
        
        while(true){
            if(!tombol_1.equals("1")) {
                break;
            }
            if(!tombol_2.equals("2")) {
                break;
            }
            if(!tombol_3.equals("3")) {
                break;
            }
            if(!tombol_4.equals("4")) {
                break;
            }
            if(!tombol_5.equals("5")) {
                break;
            }
            if(!tombol_6.equals("6")) {
                break;
            }
            if(!tombol_7.equals("7")) {
                break;
            }
            if(!tombol_8.equals("8")) {
                break;
            }
            if(!tombol_9.equals("9")) {
                break;
            }
            if(!tombol_10.equals("10")) {
                break;
            }
            if(!tombol_11.equals("11")) {
                break;
            }
            if(!tombol_12.equals("12")) {
                break;
            }
            if(!tombol_13.equals("13")) {
                break;
            }
            if(!tombol_14.equals("14")) {
                break;
            }
            if(!tombol_15.equals("15")) {
                break;
            }
            if(!tombol_16.equals("")) {
                break;
            }
            status = 1;
            break;
            
            
        }
        
        if(status == 1){
            JOptionPane.showMessageDialog(null,"Selamat, Anda telah menyelesaikan puzzle");  
            
        try{
            Class.forName(JDBC_DRIVER);

            conn = DriverManager.getConnection(DB_URL, USER, PASS);
            stmt = conn.createStatement();  
            
            String sql = " UPDATE tb_progres_4x4 SET status=0 WHERE id_user=%d" ;
            sql = String.format(sql,frameLogin.id_user);
            stmt.execute(sql);
            stmt.close();
            conn.close(); 
            
        }catch (Exception e) {
            e.printStackTrace();
        }            
            
            dispose();
            frameMainmenu hm = new frameMainmenu();
            hm.setVisible(true);
            hm.pack();
            hm.setLocationRelativeTo(null);
            hm.setDefaultCloseOperation(frameMainmenu.EXIT_ON_CLOSE);          
        }
        
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String angka = jButton1.getText();
        
        if((jButton2.getText()).equals("")){
            jButton1.setText("");
            jButton2.setText(angka);
            }
        if((jButton5.getText()).equals("")){
            jButton1.setText("");
            jButton5.setText(angka);
            }    
        
        cekSave();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String angka = jButton2.getText();
        
        if((jButton1.getText()).equals("")){
            jButton2.setText("");
            jButton1.setText(angka);
            }
        if((jButton6.getText()).equals("")){
            jButton2.setText("");
            jButton6.setText(angka);
            }    
        if((jButton3.getText()).equals("")){
            jButton2.setText("");
            jButton3.setText(angka);
            }            
                     
        cekSave();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String angka = jButton3.getText();
        
        if((jButton2.getText()).equals("")){
            jButton3.setText("");
            jButton2.setText(angka);
            }
        if((jButton7.getText()).equals("")){
            jButton3.setText("");
            jButton7.setText(angka);
            }    
        if((jButton4.getText()).equals("")){
            jButton3.setText("");
            jButton4.setText(angka);
            }            
                  
        cekSave();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String angka = jButton4.getText();
        
        if((jButton3.getText()).equals("")){
            jButton4.setText("");
            jButton3.setText(angka);
            }
        if((jButton8.getText()).equals("")){
            jButton4.setText("");
            jButton8.setText(angka);
            }            
                  
        cekSave();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String angka = jButton5.getText();
        
        if((jButton1.getText()).equals("")){
            jButton5.setText("");
            jButton1.setText(angka);
            }
        if((jButton6.getText()).equals("")){
            jButton5.setText("");
            jButton6.setText(angka);
            }    
        if((jButton9.getText()).equals("")){
            jButton5.setText("");
            jButton9.setText(angka);
            }            
               
        cekSave();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String angka = jButton6.getText();
        
        if((jButton2.getText()).equals("")){
            jButton6.setText("");
            jButton2.setText(angka);
            }
        if((jButton5.getText()).equals("")){
            jButton6.setText("");
            jButton5.setText(angka);
            }    
        if((jButton7.getText()).equals("")){
            jButton6.setText("");
            jButton7.setText(angka);
            }            
        if((jButton10.getText()).equals("")){
            jButton6.setText("");
            jButton10.setText(angka);
            }           
                    
        cekSave();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        String angka = jButton7.getText();
        
        if((jButton3.getText()).equals("")){
            jButton7.setText("");
            jButton3.setText(angka);
            }
        if((jButton6.getText()).equals("")){
            jButton7.setText("");
            jButton6.setText(angka);
            }    
        if((jButton8.getText()).equals("")){
            jButton7.setText("");
            jButton8.setText(angka);
            }            
        if((jButton11.getText()).equals("")){
            jButton7.setText("");
            jButton11.setText(angka);
            }   
        
        cekSave();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        String angka = jButton8.getText();
        
        if((jButton4.getText()).equals("")){
            jButton8.setText("");
            jButton4.setText(angka);
            }
        if((jButton7.getText()).equals("")){
            jButton8.setText("");
            jButton7.setText(angka);
            }    
        if((jButton12.getText()).equals("")){
            jButton8.setText("");
            jButton12.setText(angka);
            }            
      
        cekSave();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        String angka = jButton9.getText();
        
        if((jButton5.getText()).equals("")){
            jButton9.setText("");
            jButton5.setText(angka);
            }
        if((jButton10.getText()).equals("")){
            jButton9.setText("");
            jButton10.setText(angka);
            }    
        if((jButton13.getText()).equals("")){
            jButton9.setText("");
            jButton13.setText(angka);
            }            
             
        cekSave();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        String angka = jButton10.getText();
        
        if((jButton6.getText()).equals("")){
            jButton10.setText("");
            jButton6.setText(angka);
            }
        if((jButton9.getText()).equals("")){
            jButton10.setText("");
            jButton9.setText(angka);
            }    
        if((jButton11.getText()).equals("")){
            jButton10.setText("");
            jButton11.setText(angka);
            }   
        if((jButton14.getText()).equals("")){
            jButton10.setText("");
            jButton14.setText(angka);
            }                
          
        cekSave();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        String angka = jButton11.getText();
        
        if((jButton7.getText()).equals("")){
            jButton11.setText("");
            jButton7.setText(angka);
            }
        if((jButton10.getText()).equals("")){
            jButton11.setText("");
            jButton10.setText(angka);
            }    
        if((jButton12.getText()).equals("")){
            jButton11.setText("");
            jButton12.setText(angka);
            }   
        if((jButton15.getText()).equals("")){
            jButton11.setText("");
            jButton15.setText(angka);
            }                
          
        cekSave();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        String angka = jButton12.getText();
        
        if((jButton8.getText()).equals("")){
            jButton12.setText("");
            jButton8.setText(angka);
            }
        if((jButton11.getText()).equals("")){
            jButton12.setText("");
            jButton11.setText(angka);
            }    
        if((jButton16.getText()).equals("")){
            jButton12.setText("");
            jButton16.setText(angka);
            }               
                 
        cekSave();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        String angka = jButton13.getText();
        
        if((jButton9.getText()).equals("")){
            jButton13.setText("");
            jButton9.setText(angka);
            }
        if((jButton14.getText()).equals("")){
            jButton13.setText("");
            jButton14.setText(angka);
            }             
                  
        cekSave();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        String angka = jButton14.getText();
        
        if((jButton13.getText()).equals("")){
            jButton14.setText("");
            jButton13.setText(angka);
            }
        if((jButton10.getText()).equals("")){
            jButton14.setText("");
            jButton10.setText(angka);
            }         
        if((jButton15.getText()).equals("")){
            jButton14.setText("");
            jButton15.setText(angka);
            }            
                   
        cekSave();
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        String angka = jButton15.getText();
        
        if((jButton14.getText()).equals("")){
            jButton15.setText("");
            jButton14.setText(angka);
            }
        if((jButton11.getText()).equals("")){
            jButton15.setText("");
            jButton11.setText(angka);
            }         
        if((jButton16.getText()).equals("")){
            jButton15.setText("");
            jButton16.setText(angka);
            }            
             
        cekSave();
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        String angka = jButton16.getText();
        
        if((jButton15.getText()).equals("")){
            jButton16.setText("");
            jButton15.setText(angka);
            }
        if((jButton12.getText()).equals("")){
            jButton16.setText("");
            jButton12.setText(angka);
            }         
    
        cekSave();
    }//GEN-LAST:event_jButton16ActionPerformed

    private void KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembaliActionPerformed
        // TODO add your handling code here:
            dispose();
            frameDifficulty df = new frameDifficulty();
            df.setVisible(true);
            df.pack();
            df.setLocationRelativeTo(null);
            df.setDefaultCloseOperation(frameMainmenu.EXIT_ON_CLOSE);             
    }//GEN-LAST:event_KembaliActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        gantiRandom();
        cekSave();
    }//GEN-LAST:event_jButton17ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(framePuzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(framePuzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(framePuzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(framePuzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new framePuzzle().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Kembali;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
