/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tubesgamesederhana;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.util.Arrays;
import java.util.Random;
/**
 *
 * @author user
 */
public class framePuzzle3x3 extends javax.swing.JFrame {
    
    /**
     * Creates new form framePuzzle3x3
     */
    public framePuzzle3x3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        kembali = new javax.swing.JButton();
        judul = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambarProgram/puzzle (2).png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jButton1.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 255));
        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 255));
        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 51, 255));
        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jButton4.setForeground(new java.awt.Color(51, 51, 255));
        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jButton5.setForeground(new java.awt.Color(51, 51, 255));
        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jButton6.setForeground(new java.awt.Color(51, 51, 255));
        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jButton7.setForeground(new java.awt.Color(51, 51, 255));
        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jButton8.setForeground(new java.awt.Color(51, 51, 255));
        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jButton9.setForeground(new java.awt.Color(51, 51, 255));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        kembali.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        kembali.setText("KEMBALI");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });

        judul.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        judul.setForeground(new java.awt.Color(255, 255, 255));
        judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul.setText("SLIDER PUZZLE");

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambarProgram/puzzle (2).png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(kembali)
                    .addComponent(logo))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(judul, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(83, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(122, 122, 122))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(judul)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(kembali)
                .addGap(88, 88, 88))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    static final String JDBC_DRIVER = "com.mysql.cj.jdbc.Driver";
    static final String DB_URL = "jdbc:mysql://localhost/db_slider_puzzle";
    static final String USER = "root";
    static final String PASS = "";
    
    static Connection conn;
    static Statement stmt;
    static ResultSet rs; 
    
    public void gantiRandom(){
            int[] array = { 1, 2, 3, 4, 5, 6, 7, 8};

            Random rand = new Random();

            //https://www.journaldev.com/32661/shuffle-array-java
            for (int i = 0; i < array.length; i++) {
                    int randomIndexToSwap = rand.nextInt(array.length);
                    int temp = array[randomIndexToSwap];
                    array[randomIndexToSwap] = array[i];
                    array[i] = temp;
            }
            
            jButton1.setText(array[0]+"");
            jButton2.setText(array[1]+"");
            jButton3.setText(array[2]+"");
            jButton4.setText(array[3]+"");
            jButton5.setText(array[4]+"");
            jButton6.setText(array[5]+"");
            jButton7.setText(array[6]+"");
            jButton8.setText(array[7]+"");
            jButton9.setText("");
            
            System.out.println(Arrays.toString(array));
    }  
    
    public void gantiSave(){
        
        jButton1.setText("");
        jButton2.setText("");
        jButton3.setText("");
        jButton4.setText("");
        jButton5.setText("");
        jButton6.setText("");
        jButton7.setText("");
        jButton8.setText("");
        jButton9.setText("");
        
        try{
            Class.forName(JDBC_DRIVER);

            conn = DriverManager.getConnection(DB_URL, USER, PASS);
            stmt = conn.createStatement();  
            
               String sql = "SELECT button1, button2, button3, button4, button5, button6, button7, button8, button9 FROM tb_progres_3x3 where id_user = %d ";
               sql = String.format(sql,frameLogin.id_user);
               
               rs = stmt.executeQuery(sql);
               while(rs.next()){
                   if(rs.getInt("button1")!=0)
                        jButton1.setText(rs.getInt("button1")+"");
                   if(rs.getInt("button2")!=0)
                        jButton2.setText(rs.getInt("button2")+"");
                   if(rs.getInt("button3")!=0)
                        jButton3.setText(rs.getInt("button3")+"");
                   if(rs.getInt("button4")!=0)
                        jButton4.setText(rs.getInt("button4")+"");
                   if(rs.getInt("button5")!=0)
                        jButton5.setText(rs.getInt("button5")+"");
                   if(rs.getInt("button6")!=0)
                        jButton6.setText(rs.getInt("button6")+"");
                   if(rs.getInt("button7")!=0)
                        jButton7.setText(rs.getInt("button7")+"");
                   if(rs.getInt("button8")!=0)
                        jButton8.setText(rs.getInt("button8")+"");
                   if(rs.getInt("button9")!=0)
                        jButton9.setText(rs.getInt("button9")+"");
               }           
            
        }catch (Exception e) {
            e.printStackTrace();
        }     
       
    }
    
    private void cekSave(){
        String tombol_1 = jButton1.getText();
        String tombol_2 = jButton2.getText();
        String tombol_3 = jButton3.getText();
        String tombol_4 = jButton4.getText();
        String tombol_5 = jButton5.getText();
        String tombol_6 = jButton6.getText();
        String tombol_7 = jButton7.getText();
        String tombol_8 = jButton8.getText();
        String tombol_9 = jButton9.getText();
        int status = 0;
        
        try{
            Class.forName(JDBC_DRIVER);

            conn = DriverManager.getConnection(DB_URL, USER, PASS);
            stmt = conn.createStatement();  
            
            String sql = " UPDATE tb_progres_3x3 SET status=1, button1='%s', button2='%s', button3='%s', button4='%s', button5='%s', button6='%s', button7='%s', button8='%s', button9='%s' WHERE id_user=%d" ;
            sql = String.format(sql,tombol_1,tombol_2,tombol_3,tombol_4,tombol_5,tombol_6,tombol_7,tombol_8,tombol_9,frameLogin.id_user);
            stmt.execute(sql);
            stmt.close();
            conn.close(); 
            
        }catch (Exception e) {
            e.printStackTrace();
        }

        while(true){
            if(!tombol_1.equals("1")) {
                break;
            }
            if(!tombol_2.equals("2")) {
                break;
            }
            if(!tombol_3.equals("3")) {
                break;
            }
            if(!tombol_4.equals("4")) {
                break;
            }
            if(!tombol_5.equals("5")) {
                break;
            }
            if(!tombol_6.equals("6")) {
                break;
            }
            if(!tombol_7.equals("7")) {
                break;
            }
            if(!tombol_8.equals("8")) {
                break;
            }
            if(!tombol_9.equals("")) {
                break;
            }
            status = 1;
            break;
            
            
        }
        
        if(status == 1){
            JOptionPane.showMessageDialog(null,"Selamat, Anda telah menyelesaikan puzzle");            
            
        try{
            Class.forName(JDBC_DRIVER);

            conn = DriverManager.getConnection(DB_URL, USER, PASS);
            stmt = conn.createStatement();  
            
            String sql = " UPDATE tb_progres_3x3 SET status=0 WHERE id_user=%d" ;
            sql = String.format(sql,frameLogin.id_user);
            stmt.execute(sql);
            stmt.close();
            conn.close(); 
            
        }catch (Exception e) {
            e.printStackTrace();
        }
            
            dispose();
            frameMainmenu hm = new frameMainmenu();
            hm.setVisible(true);
            hm.pack();
            hm.setLocationRelativeTo(null);
            hm.setDefaultCloseOperation(frameMainmenu.EXIT_ON_CLOSE);          
        }
        
    }    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String angka = jButton1.getText();
        
        if((jButton2.getText()).equals("")){
            jButton1.setText("");
            jButton2.setText(angka);
            }
        if((jButton4.getText()).equals("")){
            jButton1.setText("");
            jButton4.setText(angka);
            }    
        
        cekSave();        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
            dispose();
            frameDifficulty df = new frameDifficulty();
            df.setVisible(true);
            df.pack();
            df.setLocationRelativeTo(null);
            df.setDefaultCloseOperation(frameMainmenu.EXIT_ON_CLOSE);            
    }//GEN-LAST:event_kembaliActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String angka = jButton2.getText();
        
        if((jButton1.getText()).equals("")){
            jButton2.setText("");
            jButton1.setText(angka);
            }
        if((jButton5.getText()).equals("")){
            jButton2.setText("");
            jButton5.setText(angka);
            }    
        if((jButton3.getText()).equals("")){
            jButton2.setText("");
            jButton3.setText(angka);
            }           
        
        cekSave();        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String angka = jButton3.getText();
        
        if((jButton2.getText()).equals("")){
            jButton3.setText("");
            jButton2.setText(angka);
            }
        if((jButton6.getText()).equals("")){
            jButton3.setText("");
            jButton6.setText(angka);
            }            
        
        cekSave();              
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String angka = jButton4.getText();
        
        if((jButton1.getText()).equals("")){
            jButton4.setText("");
            jButton1.setText(angka);
            }
        if((jButton5.getText()).equals("")){
            jButton4.setText("");
            jButton5.setText(angka);
            }    
        if((jButton7.getText()).equals("")){
            jButton4.setText("");
            jButton7.setText(angka);
            }           
        
        cekSave();              
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         String angka = jButton5.getText();
        
        if((jButton2.getText()).equals("")){
            jButton5.setText("");
            jButton2.setText(angka);
            }
        if((jButton4.getText()).equals("")){
            jButton5.setText("");
            jButton4.setText(angka);
            }    
        if((jButton6.getText()).equals("")){
            jButton5.setText("");
            jButton6.setText(angka);
            }
        if((jButton8.getText()).equals("")){
            jButton5.setText("");
            jButton8.setText(angka);
            }           
        
        cekSave();            
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         String angka = jButton6.getText();
        
        if((jButton3.getText()).equals("")){
            jButton6.setText("");
            jButton3.setText(angka);
            }
        if((jButton5.getText()).equals("")){
            jButton6.setText("");
            jButton5.setText(angka);
            }    
        if((jButton9.getText()).equals("")){
            jButton6.setText("");
            jButton9.setText(angka);
            }           
        
        cekSave();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        String angka = jButton7.getText();
        
        if((jButton4.getText()).equals("")){
            jButton7.setText("");
            jButton4.setText(angka);
            }
        if((jButton8.getText()).equals("")){
            jButton7.setText("");
            jButton8.setText(angka);
            }    
 
        cekSave();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
         String angka = jButton8.getText();
        
        if((jButton5.getText()).equals("")){
            jButton8.setText("");
            jButton5.setText(angka);
            }
        if((jButton7.getText()).equals("")){
            jButton8.setText("");
            jButton7.setText(angka);
            }    
        if((jButton9.getText()).equals("")){
            jButton8.setText("");
            jButton9.setText(angka);
            }           
        
        cekSave();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
         String angka = jButton9.getText();
        
        if((jButton6.getText()).equals("")){
            jButton9.setText("");
            jButton6.setText(angka);
            }
        if((jButton8.getText()).equals("")){
            jButton9.setText("");
            jButton8.setText(angka);
            }    
 
        cekSave();
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(framePuzzle3x3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(framePuzzle3x3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(framePuzzle3x3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(framePuzzle3x3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new framePuzzle3x3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel judul;
    private javax.swing.JButton kembali;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
